services:
  backend:
    image: ${ECR_REGISTRY}/netflix-clone-backend:${IMAGE_TAG:-latest}
    container_name: netflix-backend
    restart: unless-stopped
    expose:
      - '8000'
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      SERVER_PORT: 8000
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
      TMDB_API_KEY: ${TMDB_API_KEY}
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
      MAILTRAP_ENDPOINT: ${MAILTRAP_ENDPOINT}
      HTTPS: ${HTTPS:-false}
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:8000/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  frontend:
    image: ${ECR_REGISTRY}/netflix-clone-frontend:${IMAGE_TAG:-latest}
    container_name: netflix-frontend
    restart:
      unless-stopped
      # Override du CMD pour forcer allowedHosts
    command: ['bun', 'run', 'preview', '--', '--host', '0.0.0.0', '--port', '5173', '--strictPort']
    expose:
      - '5173'
    networks:
      - app-network
    depends_on:
      - backend
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  nginx:
    image: nginx:alpine
    container_name: netflix-nginx
    restart: unless-stopped
    ports:
      - '80:80' # seul nginx expose vers l'extérieur
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  app-network:
    driver: bridge
